import type {
  Bird,
  Category,
  Favorite,
  Payment,
  Transaction,
  User,
} from "@/lib/types";

export const categories: Category[] = [
  {
    id: "cat-medan",
    name: "Murai Batu Medan",
    slug: "murai-batu-medan",
    description: "Karakter suara lantang dan ekor panjang.",
  },
  {
    id: "cat-borneo",
    name: "Murai Batu Borneo",
    slug: "murai-batu-borneo",
    description: "Postur kokoh dengan variasi lagu kuat.",
  },
  {
    id: "cat-trotol",
    name: "Murai Trotol",
    slug: "murai-trotol",
    description: "Pilihan untuk dipoles sejak usia muda.",
  },
  {
    id: "cat-gacor",
    name: "Murai Gacor",
    slug: "murai-gacor",
    description: "Siap tampil dengan performa matang.",
  },
];

export const birds: Bird[] = [
  {
    id: "bird-argon",
    categoryId: "cat-medan",
    name: "Argon Medan",
    slug: "argon-medan",
    description:
      "Murai batu Medan dengan isian rapat, durasi kerja stabil, dan mental panggung bagus.",
    price: 4800000,
    location: "Kandang Sari",
    city: "Jakarta",
    age: "18 bulan",
    gender: "MALE",
    condition: "Siap lomba",
    status: "AVAILABLE",
    isFeatured: true,
    images: ["/images/bird-1.png", "/images/bird-2.png"],
    createdAt: "2026-05-10T08:00:00.000Z",
  },
  {
    id: "bird-rimba",
    categoryId: "cat-borneo",
    name: "Rimba Borneo",
    slug: "rimba-borneo",
    description:
      "Postur besar, volume tembus, dan sudah rajin bunyi pagi-sore di rumah.",
    price: 3200000,
    location: "Aviary Timur",
    city: "Bandung",
    age: "14 bulan",
    gender: "MALE",
    condition: "Gacor",
    status: "AVAILABLE",
    isFeatured: true,
    images: ["/images/bird-2.png", "/images/bird-3.png"],
    createdAt: "2026-05-12T08:00:00.000Z",
  },
  {
    id: "bird-laras",
    categoryId: "cat-trotol",
    name: "Laras Trotol",
    slug: "laras-trotol",
    description:
      "Trotolan sehat dengan ekor mulai panjang, cocok untuk penghobi yang ingin memoles dari awal.",
    price: 1450000,
    location: "Kios Melati",
    city: "Yogyakarta",
    age: "5 bulan",
    gender: "UNKNOWN",
    condition: "Trotol",
    status: "AVAILABLE",
    isFeatured: false,
    images: ["/images/bird-3.png", "/images/bird-1.png"],
    createdAt: "2026-05-08T08:00:00.000Z",
  },
  {
    id: "bird-nusa",
    categoryId: "cat-gacor",
    name: "Nusa Juara",
    slug: "nusa-juara",
    description:
      "Materi mapan dengan tembakan cililin dan kenari, cocok untuk koleksi serius.",
    price: 6500000,
    location: "Rumah Burung Nusa",
    city: "Surabaya",
    age: "24 bulan",
    gender: "MALE",
    condition: "Siap lomba",
    status: "BOOKED",
    isFeatured: true,
    images: ["/images/bird-1.png", "/images/bird-3.png"],
    createdAt: "2026-05-05T08:00:00.000Z",
  },
  {
    id: "bird-kenari",
    categoryId: "cat-medan",
    name: "Kenari Medan",
    slug: "kenari-medan",
    description:
      "Murai aktif dengan gaya tarung menonjol dan rawatan harian yang sudah stabil.",
    price: 4100000,
    location: "Aviary Selatan",
    city: "Semarang",
    age: "16 bulan",
    gender: "MALE",
    condition: "Sehat",
    status: "SOLD",
    isFeatured: false,
    images: ["/images/bird-2.png", "/images/bird-1.png"],
    createdAt: "2026-05-02T08:00:00.000Z",
  },
];

export const users: User[] = [
  {
    id: "user-buyer",
    name: "Budi Santoso",
    email: "user@muraimarket.test",
    password: "user123",
    phone: "081234567890",
    address: "Jl. Merpati No. 12",
    city: "Jakarta",
    role: "USER",
    status: "ACTIVE",
    createdAt: "2026-04-20T08:00:00.000Z",
  },
  {
    id: "user-admin",
    name: "Admin Murai",
    email: "admin@muraimarket.test",
    password: "admin123",
    phone: "081298765432",
    city: "Jakarta",
    role: "ADMIN",
    status: "ACTIVE",
    createdAt: "2026-04-18T08:00:00.000Z",
  },
  {
    id: "user-super",
    name: "Super Admin",
    email: "super@muraimarket.test",
    password: "super123",
    phone: "081255500000",
    city: "Jakarta",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    createdAt: "2026-04-15T08:00:00.000Z",
  },
  {
    id: "user-sinta",
    name: "Sinta Lestari",
    email: "sinta@example.com",
    password: "demo123",
    phone: "081277788899",
    city: "Bandung",
    role: "USER",
    status: "SUSPENDED",
    createdAt: "2026-04-28T08:00:00.000Z",
  },
];

export const favorites: Favorite[] = [
  {
    id: "fav-1",
    userId: "user-buyer",
    birdId: "bird-rimba",
    createdAt: "2026-05-13T08:00:00.000Z",
  },
];

export const transactions: Transaction[] = [
  {
    id: "trx-1001",
    invoiceNo: "INV-202605-001",
    buyerId: "user-buyer",
    birdId: "bird-nusa",
    totalPrice: 6500000,
    status: "WAITING_VERIFICATION",
    createdAt: "2026-05-11T08:00:00.000Z",
  },
  {
    id: "trx-1002",
    invoiceNo: "INV-202605-002",
    buyerId: "user-buyer",
    birdId: "bird-kenari",
    totalPrice: 4100000,
    status: "COMPLETED",
    createdAt: "2026-05-03T08:00:00.000Z",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-1001",
    transactionId: "trx-1001",
    userId: "user-buyer",
    amount: 6500000,
    paymentType: "BANK",
    paymentLabel: "BCA Virtual Account",
    bankName: "BCA",
    accountName: "Budi Santoso",
    accountNumber: "1234567890",
    proofImage: "bukti-transfer.jpg",
    proofImageUrl: "/images/bird-1.png",
    status: "WAITING_VERIFICATION",
    createdAt: "2026-05-11T09:00:00.000Z",
  },
  {
    id: "pay-1002",
    transactionId: "trx-1002",
    userId: "user-buyer",
    amount: 4100000,
    paymentType: "BANK",
    paymentLabel: "Mandiri Virtual Account",
    bankName: "Mandiri",
    accountName: "Budi Santoso",
    accountNumber: "8899001122",
    proofImage: "bukti-lunas.jpg",
    proofImageUrl: "/images/bird-2.png",
    status: "PAID",
    paidAt: "2026-05-03T12:00:00.000Z",
    createdAt: "2026-05-03T09:00:00.000Z",
  },
];
